
tables:
  - name: human
    driver: tsv
    path: human.csv
  - name: starship
    driver: tsv
    path: starship.csv
  - name: friend
    driver: tsv
    path: friend.csv

graph:
  vertices:
    - table: human
      primaryKey: id
      label: Human
      prefix: human_
    - table: starship
      primaryKey: id
      label: Starship
      prefix: starship_

  edges:
    - from: owner
      fromTable: human
      label: owns
    - from: person
      to: friend
      label: friend
      toTable: friend
    - to: owner
      toTable: human
      label: owner
