
tables:
  human:
    driver: tsv
    path: human.csv
  starship:
    driver: tsv
    path: starship.csv
  friend:
    driver: tsv
    path: friend.csv


vertices:
  - table: human
    primaryKey: id
    label: Human
    prefix: human_
  - table: starship
    primaryKey: id
    label: Starship
    prefix: starship_

edges:
  - fromTable: human
    toTable: starship
    label: owns
    fromField: owner
    toField: id
  - fromTable: starship
    toTable: human
    label: owner
    toField: owner
    fromField: id
  #- joinTable: friend
  #  fromTable: human
  #  toTable: human
  #  fromField: person
  #  toField: friend
  #  label: friend
