
tables:
  - name: human
    path: human.csv
    primaryKey: id
    label: Human
    prefix: human_
  #- name: friend
  #  path: friend.csv
  #  edges:
  #    - from: person
  #      to: friend
  #      label: friend
  #      toTable: friend
  - name: starship
    path: starship.csv
    primaryKey: id
    label: Starship
    prefix: starship_
    edges:
      #- to: owner
      #  toTable: human
      #  label: owner
      - from: owner
        fromTable: human
        label: owns
