
tables:
  - name: human
    path: human.csv
    primaryKey: id
    label: Human
    prefix: human_
  - name: friend
    path: friend.csv
    edges:
      - from: person
        to: friend
        label: friend
  - path: starship.csv
    primaryKey: id
    label: Starship
    prefix: starship_
    edges:
      - from: id
        to: owner
        toTable: human
        label: owner
      - from: owner
        fromTable: human
        to: id
        label: owns
