
tables:
  human:
    driver: tsv
    path: human.csv
  starship:
    driver: tsv
    path: starship.csv
  #friend:
  #  driver: tsv
  #  path: friend.csv


vertices:
  human_ :
    table: human
    primaryKey: id
    label: Human
  starship_ :
    table: starship
    primaryKey: id
    label: Starship

edges:
  owns:
    fromVertex: starship_
    toVertex: human_
    label: owner
    backLabel: owns
    toField: id
    fromField: owner
  #- joinTable: friend
  #  fromTable: human
  #  toTable: human
  #  fromField: person
  #  toField: friend
  #  label: friend
