
tables:
  gdccase:
    driver: web
    config:
      list:
        url: https://api.gdc.cancer.gov/cases
        elementList: "$.data.hits"
      get:
        id:
          url: https://api.gdc.cancer.gov/cases
          params:
            filters: >
              {
                 "op":"in",
                 "content":{
                    "field":"case_id",
                    "value":["{{id}}"]
                 }
              }
          element: "$.data.hits[0]"

  gdc_smm_occurance:
    driver: web
    config:
      get:
        case_id:
          url: https://api.gdc.cancer.gov/ssm_occurrences
          params:
            expand: case
            filters: >
              {
                 "op":"in",
                 "content":{
                    "field":"case.case_id",
                    "value":["{{case_id}}"]
                 }
              }
          elementList: "$.data.hits"

        ssm_occurrence_id:
            url: https://api.gdc.cancer.gov/ssm_occurrences
            params:
              expand: case
              filters: >
                {
                   "op":"in",
                   "content":{
                      "field":"ssm_occurrence_id",
                      "value":["{{ssm_occurrence_id}}"]
                   }
                }
            element: "$.data.hits[0]"

  pdccase:
    driver: web
    config:
      list:
        url: https://pdc.esacinc.com/graphql
        elementList: "$.data.allCases"
        params:
          query: "{allCases {case_id case_submitter_id project_submitter_id disease_type primary_site}}"


vertices:
  "case:" :
    table: gdccase
    primaryKey: id
    label: Case

  "pdccase:" :
    table: pdccase
    primaryKey: case_id
    label: PDCCase

  "ssm_occurrence:" :
    table: gdc_smm_occurance
    primaryKey: ssm_occurrence_id
    label: SSMoccurrence

edges:
  ssms:
    fromVertex: "case:"
    toVertex: "ssm_occurrence:"
    label: ssms
    toField: case_id
    fromField: id
