
tables:
  gdccase:
    driver: web
    config:
      list:
        url: https://api.gdc.cancer.gov/cases
        elementList: "$.data.hits"

  gdc_smms_occurance:
    driver: web
    config:
      get:
        url: https://api.gdc.cancer.gov/ssm_occurrences
        params:
          expand: case
        templateParams:
          op: in
          content:
            field: case.submitter_id
            value: ["$.id"]


  pdccase:
    driver: web
    config:
      list:
        url: https://pdc.esacinc.com/graphql
        elementList: "$.data.allCases"
        params:
          query: "{allCases {case_id case_submitter_id project_submitter_id disease_type primary_site}}"


vertices:
  "case:" :
    table: gdccase
    primaryKey: id
    label: Case

  "pdccase:" :
    table: pdccase
    primaryKey: case_id
    label: PDCCase
