
tables:
  gdccase:
    driver: web
    config:
      list:
        url: https://api.gdc.cancer.gov/cases
        elementList: "$.data.hits"
        params:
          size: "100"
        cache: true
        pager:
          code: >
            def pager(url, result):
              p = result['data']['pagination']
              if p['page'] >= p['pages']:
                return None
              return { "from" : p["from"] + p["count"] }
          method: pager
      get:
        id:
          url: https://api.gdc.cancer.gov/cases
          params:
            filters: >
              {
                 "op":"in",
                 "content":{
                    "field":"case_id",
                    "value":["{{id}}"]
                 }
              }
          element: "$.data.hits[0]"
        submitter_id:
          url: https://api.gdc.cancer.gov/cases
          params:
            filters: >
              {
                 "op":"in",
                 "content":{
                    "field":"submitter_id",
                    "value":["{{submitter_id}}"]
                 }
              }
          elementList: "$.data.hits"


  gdc_smm_occurance:
    driver: web
    config:
      get:
        case_id:
          url: https://api.gdc.cancer.gov/ssm_occurrences
          params:
            expand: case
            filters: >
              {
                 "op":"in",
                 "content":{
                    "field":"case.case_id",
                    "value":["{{case_id}}"]
                 }
              }
          elementList: "$.data.hits"

        ssm_occurrence_id:
            url: https://api.gdc.cancer.gov/ssm_occurrences
            params:
              expand: case
              filters: >
                {
                   "op":"in",
                   "content":{
                      "field":"ssm_occurrence_id",
                      "value":["{{ssm_occurrence_id}}"]
                   }
                }
            element: "$.data.hits[0]"

  ssm:
    driver: web
    config:
      get:
        cosmic_id:
          url: https://api.gdc.cancer.gov/ssms
          params:
            filter: >
              {
                "op":"in",
                "content":{
                  "field":"cosmic_id",
                  "value":[
                     "{{cosmic_id}}"
                  ]
               }

  pdccase:
    driver: web
    config:
      list:
        url: https://pdc.esacinc.com/graphql
        elementList: "$.data.allCases"
        params:
          query: "{allCases {case_id case_submitter_id project_submitter_id disease_type primary_site}}"

  pdcproject:
    driver: web
    config:
      list:
        url: https://pdc.esacinc.com/graphql
        elementList: "$.data.projectsPerExperimentType"
        params:
          query: "{projectsPerExperimentType{experiment_type project_submitter_id name}}"
        cache: True

  pdcspectra:
    driver: web
    config:
      get:
        gene:

          params:
            query: >
              query {
                getPaginatedUIGeneStudySpectralCount(gene_name:"{{gene}}") {
                  total
                  spectralCounts {
                    gene_name
                    study_submitter_id
                    project_submitter_id
                    aliquot_id
                    plex
                    spectral_count
                    distinct_peptide
                    unshared_peptide
                  }
                }
              }

  hugo:
    driver: web
    config:
      get:
        symbol:
          url: http://rest.genenames.org/fetch/symbol/{{symbol}}
          headers:
            - "Accept:application/json"
          params:
            format: json
          element: "$.response.docs[0]"

vertices:
  "gdc.cancer.gov/case/" :
    table: gdccase
    primaryKey: id
    label: Case

  "pdc.esacinc.com/case/" :
    table: pdccase
    primaryKey: case_id
    label: PDCCase

  "pdc.esacinc.com/project/" :
    table: pdcproject
    primaryKey: project_submitter_id
    label: PDCProject


  "gdc.cancer.gov/ssm_occurrence/" :
    table: gdc_smm_occurance
    primaryKey: ssm_occurrence_id
    label: SSMoccurrence

  "genenames.org/gene/" :
    table: hugo
    primaryKey: symbol
    label: Gene

edges:
  ssms:
    fromVertex: "gdc.cancer.gov/case/"
    toVertex: "gdc.cancer.gov/ssm_occurrence/"
    label: ssms
    toField: case_id
    fromField: id

  gdcRecord:
    fromVertex: "pdc.esacinc.com/case/"
    toVertex: "gdc.cancer.gov/case/"
    label: "gdcRecord"
    fromField: case_submitter_id
    toField: submitter_id
