name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./

    - name: Python Dependencies for Conformance
      run: pip install requests numpy


  badgerTest:
    needs: build
    name: Badger Conformance
    runs-on: ubuntu-latest
    steps:
    - name: Badger Test
      run: |
        ./grip server --rpc-port 18202 --http-port 18201 --config ./test/badger.yml &
        sleep 5
        make test-conformance


  mongoTest:
    needs: build
    name: Mongo Conformance
    steps:
    - name: Mongo Conformance
      run: |
        make start-mongo
        ./grip server --rpc-port 18202 --http-port 18201 --config ./test/mongo.yml &
        sleep 5
        make test-conformance
