name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./

    - name: Store grip
      uses: actions/upload-artifact@v2
      with:
        name: gripBin
        path: grip

  badgerTest:
    needs: build
    name: Badger Conformance
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Python Dependencies for Conformance
      run: pip install requests numpy
    - name: Download grip
      uses: actions/download-artifact@v2
      with:
        name: gripBin
    - name: Badger Test
      run: |
        chmod +x grip
        ./grip server --rpc-port 18202 --http-port 18201 --config ./test/badger.yml &
        sleep 5
        make test-conformance

  mongoTest:
    needs: build
    name: Mongo Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Python Dependencies for Conformance
      run: pip install requests numpy
    - name: Download grip
      uses: actions/download-artifact@v2
      with:
        name: gripBin
    - name: Mongo Conformance
      run: |
        chmod +x grip
        make start-mongo
        ./grip server --rpc-port 18202 --http-port 18201 --config ./test/mongo.yml &
        sleep 5
        make test-conformance

  gripperTest:
    needs: build
    name: Gripper Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Python Dependencies for Conformance
      run: pip install requests numpy
    - name: Download grip
      uses: actions/download-artifact@v2
      with:
        name: gripBin
    - name: Gripper Conformance
      run: |
        chmod +x grip
        make start-gripper-test
        sleep 5
        grip server --rpc-port 18202 --http-port 18201 --config ./gripper/test-graph/config.yaml &
        sleep 5
        python conformance/run_conformance.py http://localhost:18201 --readOnly swapi
